assign_people: assign_people_to_work_and_school.cpp
	g++ -O2 --std=c++17 assign_people_to_work_and_school.cpp -o assign_people

swap: determine_immunity_swap_probs.cpp
	g++ -g determine_immunity_swap_probs.cpp -o generate_swap_file

swap_omp: determine_immunity_swap_probs.cpp
	g++ -O2 -fopenmp determine_immunity_swap_probs.cpp -o generate_swap_file_omp
